# Numpy

- Supports for arrays and matrices. 
- Focuses on vectors and arrays

In [29]:
!pip install numpy

In [30]:
import numpy as np

# Create array using numpy

# 1-D Aray

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [31]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [43]:
# 1-D Array
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [45]:
# 2-D Array
arr2 = np.array([[1,2,3,4,6,5],[0,2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 6 5]
 [0 2 3 4 5 6]]
(2, 6)


In [50]:
# Arrange function

np.arange(0,10,2).reshape(5,1)



array([[0],
       [2],
       [4],
       [6],
       [8]])

In [52]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
# Identity Matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
# Attributes of numpy

arr = np.array([[1,2,3],[4,5,6],[41,65,24]])

print('Array:\n', arr)
print('Shape:\n', arr.shape) # Output: (2,3)

print('Number of dimensions: ', arr.ndim) # Output: 2
print('Size (number of elements) : ', arr.size)
print('Data type:', arr.dtype)   # int64

print("Item size (in bytes):", arr.itemsize) # Output 8 (vary based on platform)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [41 65 24]]
Shape:
 (3, 3)
Number of dimensions:  2
Size (number of elements) :  9
Data type: int64
Item size (in bytes): 8


In [76]:
# Numpy Vectorized Operations

arr1 =  np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition

print("Addition: ", arr1 + arr2)

# Element wise substraction
print('Substraction: ', arr1-arr2)

# Element wise multiplication
print('Multiplication: ', arr1*arr2)


# Element wise division
print('Division: ', arr1/arr2)


Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [82]:
# Universal Functions

arr = np.array([2,3,4,5,6])
# square root
print('Square Root: "\n"', np.sqrt(arr), '\n')

# Exponential
print('Exponentiation: "\n"', np.exp(arr), '\n')  # e^x exponent

# Sine
print('Sine: "\n"', np.sin(arr), '\n')

# natural log
print('Natural Log: "\n"', np.log(arr), '\n')

Square Root: "
" [1.41421356 1.73205081 2.         2.23606798 2.44948974] 

Exponentiation: "
" [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349] 

Sine: "
" [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ] 

Natural Log: "
" [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947] 



In [85]:
# Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print("array: \n", arr)

array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
print('1: \n', arr[0][0],'\n')

print('2: \n', arr[0:2,2:4],'\n')
print('3: \n', arr[1:,2:],'\n')

print('4: \n', arr[1:3,1:3])

1: 
 1 

2: 
 [[3 4]
 [7 8]] 

3: 
 [[ 7  8]
 [11 12]] 

4: 
 [[ 6  7]
 [10 11]]


In [109]:
# Modify array elements 

arr[0,0] = 100

print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [111]:
arr[1:,] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [118]:
# Statistical Concept Normalization

data = np.array([1,2,3,4,5])

# To have a mean of 0 and standard deviation of 1

# Calculate the mean and Standard Deviation

mean = np.mean(data)
std_dev =  np.std(data)
var =  np.var(data)  # Variance

print(mean)
print(std_dev)
print(var)


# Normalize the data

normalized_data = (data - mean) / std_dev
print('Variance: ', var)
print('Normalized data; ', normalized_data)



3.0
1.4142135623730951
2.0
Variance:  2.0
Normalized data;  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [124]:
# Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])